version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=Clothway
      - POSTGRES_DB=gorm
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  server:
    build: ./sources/Back/
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
    depends_on:
      - db

  client_web:
    build: ./sources/web-front/
    ports:
      - "8081:3000"
    restart: always
    networks:
      - backend
    depends_on:
      - server

  client_mobile:
    build: ./sources/app/
    restart: always
    networks:
      - backend
    command: tail -f /dev/null
    

networks:
  backend:

volumes:
  area:
  db:
    driver: local